// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZryR2GY1vr1gEXlICliz1kaycwKTE3bk',
    appId: '1:517086634952:web:d515a851c936915943d6fd',
    messagingSenderId: '517086634952',
    projectId: 'studyup-584d3',
    authDomain: 'studyup-584d3.firebaseapp.com',
    storageBucket: 'studyup-584d3.appspot.com',
    measurementId: 'G-0WJC452X03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QMLyF_uah8_b2xSn11Y6EmwwNRQNd2k',
    appId: '1:517086634952:android:0e1c4f68ba75028643d6fd',
    messagingSenderId: '517086634952',
    projectId: 'studyup-584d3',
    storageBucket: 'studyup-584d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0Getzrdekuv1plpsDCvBUH3CZFlK7m4',
    appId: '1:517086634952:ios:64ec7ee85ca2658143d6fd',
    messagingSenderId: '517086634952',
    projectId: 'studyup-584d3',
    storageBucket: 'studyup-584d3.appspot.com',
    iosClientId: '517086634952-8sttp7fqdjmsb6r9rgbhbpk5a6nb059n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0Getzrdekuv1plpsDCvBUH3CZFlK7m4',
    appId: '1:517086634952:ios:64ec7ee85ca2658143d6fd',
    messagingSenderId: '517086634952',
    projectId: 'studyup-584d3',
    storageBucket: 'studyup-584d3.appspot.com',
    iosClientId: '517086634952-8sttp7fqdjmsb6r9rgbhbpk5a6nb059n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
